### ISSUE TITLE
All sound paths outside ./Interface now throw errors

### ISSUE THREAD

**Issue by speedwaystar** [Ravendwyr/Broker_uClock#2]
the LibSharedMedia registers in Core.lua all fail when called, since filenames outside .\Interface are no longer supported.

**Comment by Ravendwyr** [comment]
Aye, this was a change in 8.2 that I was not aware of until the last possible minute. Poking the addon to pick up the latest LibSharedMedia file from CurseForge should do the trick.

_famous last words_

**Comment by speedwaystar** [comment]
out of interest, where do you find the PlaySoundFile ID for, say "Blizzard:
Alarm Clock 1" = 567436. If I look up the sound on WowHead it gives 18871
as the soundKitID, which works with PlaySound, but not with PlaySoundFile.

**Comment by speedwaystar** [comment]
nm, found it:  https://wow.gamepedia.com/FileDataID

**Comment by Ravendwyr** [comment]
No worries. I got the list from [WoW Tools](https://wow.tools/files/).
